### ISSUE TITLE
Css is not working 

### ISSUE THREAD

**Issue by diwacreation3** [ashish-shr/RealAssist-Landing-Page#1]
![Screenshot_20231003-144913_Chrome](https://github.com/ashish-shr/RealAssist-Landing-Page/assets/70707789/d8bcc6d2-0b09-4e8e-aa68-7d8d62861ac6)
I tested that page on my mobile .
I think it is not showing css on page ???
Still on development or some kind of error 👀

**Comment by ashish-shr** [comment]
still in development⚙️, that's why.
